# Generated by Django 6.0.3 on 2026-06-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado')], default='PENDENTE', max_length=20)),
                ('confirmado_por', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('WEBHOOK', 'Webhook do gateway')], max_length=20)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartao')], max_length=10)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='jobs.job')),
            ],
        ),
    ]
