# Generated by Django 6.0.3 on 2026-06-19 22:56

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ORCAMENTO_APROVADO', 'Orcamento aprovado'), ('CONTRATO_PENDENTE', 'Contrato pendente'), ('CONTRATO_ASSINADO', 'Contrato assinado'), ('EM_PRODUCAO', 'Em producao'), ('AGUARDANDO_SELECAO', 'Aguardando selecao'), ('SELECAO_CONCLUIDA', 'Selecao concluida'), ('EM_EDICAO', 'Em edicao'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('ENTREGUE', 'Entregue'), ('CONCLUIDO', 'Concluido')], default='ORCAMENTO_APROVADO', max_length=30)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.cliente')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='orcamentos.orcamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BRUTA', 'Bruta'), ('EDITADA', 'Editada')], max_length=10)),
                ('arquivo', models.FileField(upload_to=jobs.models.arquivo_foto_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=jobs.models.arquivo_foto_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='jobs.job')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
