# Generated by Django 6.0.3 on 2026-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_arquivofoto_arquivo_protegido'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data_producao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='quantidade_fotos_incluidas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='valor_foto_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
