# Generated by Django 6.0.3 on 2026-06-19 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado')], default='PENDENTE', max_length=20)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assinatura_nome', models.CharField(blank=True, max_length=120)),
                ('assinatura_cpf', models.CharField(blank=True, max_length=20)),
                ('assinatura_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('assinatura_data', models.DateTimeField(blank=True, null=True)),
                ('hash_documento', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='jobs.job')),
            ],
        ),
    ]
