# Generated by Django 6.0.3 on 2026-06-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_asaas_account_id_user_asaas_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perfis/logos/')),
                ('cor_primaria', models.CharField(default='#1d4ed8', max_length=7)),
                ('fotografo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
