# Generated by Django 6.0.3 on 2026-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilfotografo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilfotografo',
            name='cor_secundaria',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='perfilfotografo',
            name='fonte_titulo',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Playfair Display', 'Playfair Display'), ('Montserrat', 'Montserrat'), ('Lato', 'Lato'), ('Raleway', 'Raleway')], default='Inter', max_length=40),
        ),
        migrations.AddField(
            model_name='perfilfotografo',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10),
        ),
    ]
