# Generated by Django 6.0.3 on 2026-06-23 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfilfotografo_cor_secundaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilfotografo',
            name='cor_primaria',
            field=models.CharField(default='#1d4ed8', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal valida, como #FFFFFF.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='perfilfotografo',
            name='cor_secundaria',
            field=models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal valida, como #FFFFFF.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='perfilfotografo',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('custom', 'Personalizado')], default='light', max_length=10),
        ),
    ]
