# Generated by Django 6.0.3 on 2026-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='quantidade_fotos_incluidas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_foto_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
