# Generated by Django 6.0.3 on 2026-06-19 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('LIBERADO', 'Liberado')], default='BLOQUEADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_entrega', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluida')], default='PENDENTE', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selecao', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='SelecaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecionado', models.BooleanField(default=False)),
                ('arquivo_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_selecao', to='jobs.arquivofoto')),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='deliveries.selecao')),
            ],
            options={
                'unique_together': {('selecao', 'arquivo_foto')},
            },
        ),
    ]
