# Generated by Django 6.0.3 on 2026-06-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='max_fotos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracaoMarcaDagua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_png', models.ImageField(upload_to='marcas_dagua/')),
                ('opacidade', models.PositiveSmallIntegerField(default=50)),
                ('posicao', models.CharField(choices=[('centro', 'Centro'), ('superior_esq', 'Superior esquerdo'), ('superior_dir', 'Superior direito'), ('inferior_esq', 'Inferior esquerdo'), ('inferior_dir', 'Inferior direito')], default='inferior_dir', max_length=20)),
                ('tamanho_pct', models.PositiveSmallIntegerField(default=20)),
                ('fotografo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marca_dagua', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
