# Generated by Django 6.0.3 on 2026-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_selecao_max_fotos_configuracaomarcadagua'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaomarcadagua',
            name='espacamento_pct',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracaomarcadagua',
            name='modo',
            field=models.CharField(choices=[('unico', 'Posição única'), ('grade', 'Grade (repetir em toda a foto)')], default='unico', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracaomarcadagua',
            name='rotacao',
            field=models.SmallIntegerField(default=-30),
        ),
    ]
