# Generated by Django 6.0.3 on 2026-06-23 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_configuracaomarcadagua_espacamento_pct_and_more'),
        ('jobs', '0003_job_data_producao_job_quantidade_fotos_incluidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoBracketingFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='selecaoitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='selecaoitem',
            name='arquivo_foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_selecao', to='jobs.arquivofoto'),
        ),
        migrations.CreateModel(
            name='GrupoBracketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_como_capa', to='jobs.arquivofoto')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_bracketing', to='jobs.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='selecaoitem',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_selecao', to='deliveries.grupobracketing'),
        ),
        migrations.AddConstraint(
            model_name='selecaoitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('arquivo_foto__isnull', False), ('grupo__isnull', True)), models.Q(('arquivo_foto__isnull', True), ('grupo__isnull', False)), _connector='OR'), name='selecao_item_exatamente_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='selecaoitem',
            constraint=models.UniqueConstraint(fields=('selecao', 'arquivo_foto'), name='uniq_selecao_arquivo_foto'),
        ),
        migrations.AddConstraint(
            model_name='selecaoitem',
            constraint=models.UniqueConstraint(fields=('selecao', 'grupo'), name='uniq_selecao_grupo_bracketing'),
        ),
        migrations.AddField(
            model_name='grupobracketingfoto',
            name='arquivo_foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_bracketing', to='jobs.arquivofoto'),
        ),
        migrations.AddField(
            model_name='grupobracketingfoto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='deliveries.grupobracketing'),
        ),
        migrations.AlterUniqueTogether(
            name='grupobracketingfoto',
            unique_together={('grupo', 'arquivo_foto')},
        ),
    ]
